[package]
name = "gm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term-table = "1.3.2"
dirs = "4.0.0"
configparser = "3.0.0"
clap = { version = "3.0.7", features = ["derive"] }